import type { LegalDocument } from "@/lib/legal/types";

/** Sourced from https://vathala.com/privacy-policy */
export const privacyPolicy: LegalDocument = {
  title: "Privacy Policy",
  lastUpdated: "March 9, 2023",
  intro:
    "This Privacy Policy applies to Muniah Technologies / Apps platform including www.muniahtech.com and other related Sites / Apps and mobile application. The Privacy Policy is provided and controlled by MUNIAH TECHNOLOGIES. By visiting and/or using our Site, you agree to this Privacy Policy.",
  blocks: [
    {
      type: "heading",
      level: 2,
      text: "Interpretation and Definitions",
    },
    {
      type: "heading",
      level: 3,
      text: "Interpretation",
    },
    {
      type: "paragraph",
      text: "The words of which the initial letter is capitalized have meanings defined under the following conditions. The following definitions shall have the same meaning regardless of whether they appear in singular or in plural.",
    },
    {
      type: "heading",
      level: 3,
      text: "Definitions",
    },
    {
      type: "paragraph",
      text: "For the purposes of this Privacy Policy:",
    },
    {
      type: "list",
      items: [
        '"Account" means a unique account created for You to access our Service or parts of our Service.',
        '"Application" means the software program provided by the Company downloaded by You on any electronic device, named Muniah Technologies MobileApp.',
        '"Company" (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to Muniah Technologies.',
        '"Country" refers to Muniah Technologies India.',
        '"Cookies" are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.',
        '"Device" means any device that can access the Service such as a computer, a cell phone or a digital tablet.',
        '"Personal Data" is any information that relates to an identified or identifiable individual or family or business employee details.',
        '"Service" refers to the mobile Application / Websites.',
        '"Service Provider" means any natural or legal person who processes the data on behalf of the Company.',
        '"Usage Data" refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself (for example, the duration of a page visit).',
        '"You" means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.',
      ],
    },
    {
      type: "heading",
      level: 2,
      text: "Usage Data",
    },
    {
      type: "paragraph",
      text: "Usage Data is collected automatically when using the Service. Usage Data may include information such as Your Device Internet Protocol address (e.g. IP address), browser type, browser version, the pages of our Service that You visit, the time and date of Your visit, the time spent on those pages, unique device identifiers and other diagnostic data. When You access the Service by or through a mobile device, We may collect certain information automatically, including, but not limited to, the type of mobile device You use, Your mobile device unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile Internet browser You use, unique device identifiers and other diagnostic data.",
    },
    {
      type: "heading",
      level: 2,
      text: "Information Collected while Using the Application",
    },
    {
      type: "paragraph",
      text: "While using Our Application, in order to provide features of Our Application, We may collect, with Your prior permission, information regarding your location. We use this information to provide features of Our Service, to improve and customize Our Service. The information may be uploaded to the Company servers and/or a Service Provider server or it may be simply stored on Your device.",
    },
    {
      type: "heading",
      level: 2,
      text: "Use of Your Personal Data",
    },
    {
      type: "paragraph",
      text: "The Company may use Personal Data for the following purposes: for other purposes such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our Service, products, services, marketing and your experience. We may share Your personal information in the following situations:",
    },
    {
      type: "list",
      items: [
        "With Service Providers: We may share Your personal information with Service Providers to monitor and analyze the use of our Service, for payment processing, to contact You.",
        "For business transfers: We may share or transfer Your personal information in connection with, or during negotiations of, any merger, sale of Company assets, financing, or acquisition of all or a portion of Our business to another company.",
        "With Affiliates: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.",
        "With business partners: We may share Your information with Our business partners to offer You certain products, services or promotions.",
        "With other users: when You share personal information or otherwise interact in the public areas with other users, such information may be viewed by all users and may be publicly distributed outside.",
        "With Your consent: We may disclose Your personal information for any other purpose with Your consent.",
      ],
    },
    {
      type: "heading",
      level: 2,
      text: "Retention of Your Personal Data",
    },
    {
      type: "paragraph",
      text: "The Company will retain Your Personal Data only for as long as is necessary for the purposes set out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies. The Company will also retain Usage Data for internal analysis purposes.",
    },
    {
      type: "heading",
      level: 2,
      text: "Links to Other Websites",
    },
    {
      type: "paragraph",
      text: "Our Service may contain links to other websites that are not operated by Us. If You click on a third party link, You will be directed to that third party site. We strongly advise You to review the Privacy Policy of every site You visit. We have no control over and assume no responsibility for the content, privacy policies or practices of any third party sites or services.",
    },
    {
      type: "heading",
      level: 2,
      text: "Changes to this Privacy Policy",
    },
    {
      type: "paragraph",
      text: "We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new Privacy Policy on this page. We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming effective and update the \"Last updated\" date at the top of this Privacy Policy.",
    },
    {
      type: "heading",
      level: 2,
      text: "The Information we do collect",
    },
    {
      type: "paragraph",
      text: "When you subscribe to our packages, we collect the personal information you give us such as your name, address and email address. With your permission, we may email you regarding new updates and other. We may catch your IP address to get personal information that makes us learn more about you when you visit us through browser to subscribe to our package.",
    },
    {
      type: "heading",
      level: 2,
      text: "Consent",
    },
    {
      type: "paragraph",
      text: "When you provide us with personal information to complete a transaction, verify your credit/debit cards, we imply that you consent to our collecting it and using it for that specific reason only.",
    },
    {
      type: "heading",
      level: 2,
      text: "Disclosure",
    },
    {
      type: "paragraph",
      text: "We may disclose your personal information if we are required by law to do so or if you violate our Terms of Service.",
    },
    {
      type: "heading",
      level: 2,
      text: "Cookies",
    },
    {
      type: "paragraph",
      text: "We use cookies to maintain sessions of users. It is not used to personally identify you on other websites.",
    },
    {
      type: "heading",
      level: 2,
      text: "Age of Consent",
    },
    {
      type: "paragraph",
      text: "By using our service, you represent that you are at least the age of majority in your state or province of residence.",
    },
    {
      type: "heading",
      level: 2,
      text: "Security",
    },
    {
      type: "paragraph",
      text: "The security of your personal information is important to us. When you enter your personal information, we treat the data as an asset that must be protected and use tools (encryption, passwords, physical security, etc.) to protect your personal information against unauthorized access and disclosure.",
    },
    {
      type: "heading",
      level: 2,
      text: "Contact Us",
    },
    {
      type: "paragraph",
      text: "All questions, comments and requests regarding this policy should be addressed to:",
    },
    {
      type: "list",
      items: [
        "Mailing Address: Muniah Technologies Pvt Ltd, No.3, 4th Main Road, Kottur Gardens, 1st Floor, Above NILGIRIS, Kotturpuram, Chennai, Tamil Nadu 600085, India",
        "Email Address: muniahtechnologies@gmail.com",
      ],
    },
  ],
};
